<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows10.0.19041.0</TargetFramework>
    <TargetPlatformMinVersion>10.0.17763.0</TargetPlatformMinVersion>
    <RootNamespace>WinUIBatchPacker</RootNamespace>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <Platforms>x64</Platforms>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <UseWinUI>true</UseWinUI>
    <WindowsPackageType>None</WindowsPackageType>
    <EnableMsixTooling>true</EnableMsixTooling>
    <WindowsAppSDKSelfContained>false</WindowsAppSDKSelfContained>
    <SelfContained>false</SelfContained>
    <PublishTrimmed>false</PublishTrimmed>
    <DebugType>none</DebugType>
    <DebugSymbols>false</DebugSymbols>
    <InvariantGlobalization>true</InvariantGlobalization>
    <UseSystemResourceKeys>true</UseSystemResourceKeys>
    <EventSourceSupport>false</EventSourceSupport>
    <MetadataUpdaterSupport>false</MetadataUpdaterSupport>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.WindowsAppSDK" Version="1.8.260804001" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="FontSubsetCore\FontSubsetCore.csproj" />
    <ProjectReference Include="ThirdParty\SevenZipExtractor\SevenZipExtractor.csproj" />
    <Compile Remove="FontSubsetCore\**\*.cs" />
    <Compile Remove="ThirdParty\SevenZipExtractor\**\*.cs" />
    <EmbeddedResource Include="ThirdParty\7Zip\7z.dll" LogicalName="WinUIBatchPacker.7z.dll" />
  </ItemGroup>
</Project>
